stages:    
    - build
    - deploy

variables:
    IMAGE_NAME: federicogfb/mis-practicas
    IMAGE_TAG: latest

build_docker_image:
    image: docker:24.0.2-cli
    stage: build
    services:
        - docker:24.0.2-dind
    variables:
      DOCKER_TLS_CERTDIR: "/certs"
    before_script:
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_to_minikube:
    stage: deploy
    image: lachlanevenson/k8s-kubectl:v1.21.2  # An image with kubectl installed
    script:
        - export KUBECONFIG=/kubeconfig.yaml  # Set KUBECONFIG to point to the shared kubeconfig
        - kubectl apply -f ./deployment/
