apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: app-frontend
  name: app-frontend
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/5-desafio-mynet: "true"
        io.kompose.service: app-frontend
    spec:
      containers:
        - image: app-frontend
          name: app-frontend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
