name: build and push into DockerHub

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image 1
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./backend/  # Path to the directory with Dockerfile 1
          dockerfile: ./backend/Dockerfile  # Path to Dockerfile 1
          tags: federicogfb/practica-ci-jenkins:image1

      - name: Build and push Docker image 2
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./frontend/  # Path to the directory with Dockerfile 2
          dockerfile: ./frontend/Dockerfile  # Path to Dockerfile 2
          tags: federicogfb/practica-ci-jenkins:image2
  
  minikube:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Minikube
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
          namespace="prod"
        else [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
          namespace="dev"
        fi

        kubectl apply -f ./deployment/ -n "$namespace"
